#!/bin/bash

if [[ $# == 0 || $1 == "-h" || $1 == "--help" ]]; then
    echo "usage: $(basename $0) <path>"
    exit 0
fi

path_to_file=$(realpath $1)

# relocating on the executable directory
cd $(dirname $(readlink -f $0))/src/

./legolas $path_to_file

